/*
Users Table
Feilds: UserID, Name, Password stored in encrypted format
Primary Key: UserId
*/

CREATE TABLE Users (
	UserID		int				IDENTITY (1, 1) not null,
	ASPIdentityID	nvarchar(100)	not null, /*Populated by copying the UserID from Asp Identity, not a FK*/
	PRIMARY KEY (UserID ASC)
);

/*
Colleges Table
Feilds: CollegeID, Name, StateName, City, Accreditor, Focus, Ownership, Cost, Favorite, Saved, UserId, College_UserID
Primary Key: CollegeID
Foreign Key: UserID
*/
CREATE TABLE Colleges (
	CollegeID	int				IDENTITY (1, 1) not null,
	Name		nvarchar(150)	not null,
	StateName	nvarchar(30)	not null,
	City		nvarchar(25)	not null, /*Obtained from SearchForm field.*/
	Accreditor	nvarchar(25),
	Focus		nvarchar(50), /*Obtained from SearchForm field.*/
	Ownership	int				not null, /*1 is Public, 2 is Private NP, 3 is Private FP*/
	Cost		int				not null,
	AdmissionRate	int,
	PRIMARY KEY (CollegeID ASC)
);

/*
College_User_Relations Table
Feilds: UserID, CollegeID
Primary Key: UserId, CollegeID
*/
CREATE TABLE College_User_Relations (
	UserID		int				not null,
	CollegeID	int				not null,
	Favorite	bit				not null, /*0 is False, 1 is True*/
	Saved		bit				not null, /*0 is False, 1 is True*/
	CONSTRAINT College_UserID PRIMARY KEY (UserID, CollegeID), /*PK generated by both keys as a relationship.*/
	CONSTRAINT FK_CollegeID FOREIGN KEY (CollegeID) REFERENCES Colleges(CollegeID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID)
	ON UPDATE CASCADE ON DELETE CASCADE	
);

/*=========INSERT SCRIPTS==============*/

INSERT INTO Users(ASPIdentityID) VALUES (
	'221b'
);

INSERT INTO Colleges(Name, StateName, City, Accreditor, Focus, Ownership, Cost, AdmissionRate) VALUES (
	'Hyrule University', 'Hyrule', 'Kakariko', 'Malon Foundation', 'Business', 1, 20000, 80
);

INSERT INTO College_User_Relations (UserID, CollegeID, Favorite, Saved) VALUES (
	1, 1, 0, 0
);
